basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: API to analyze and manage stocks
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Stock Analyzer API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
